# Generated by Django 4.1.7 on 2023-03-20 07:55

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='backend/users/backend/static/img/%Y/%m/%d')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('avatar', models.ImageField(blank=True, upload_to='backend/users/backend/static/img/%Y/%m/%d')),
                ('is_banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.country')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='backend/users/backend/static/icon')),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('app_label', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.companyuser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.companyuser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_friends', to='developers.companyuser')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_friends', to='developers.companyuser')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.contacttype')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.contacts')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='developers.companyuser'),
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='developers.companyuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.company')),
            ],
        ),
    ]
