# Generated by Django 4.1.7 on 2023-03-21 10:48

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperGroupPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'developer group permission',
                'verbose_name_plural': 'developer group permissions',
                'db_table': 'developer_group_permission',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeveloperPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'developer permission',
                'verbose_name_plural': 'developer permissions',
                'db_table': 'developer_permission',
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Friends',
            new_name='DeveloperFriends',
        ),
        migrations.RenameModel(
            old_name='GroupUserPermissions',
            new_name='DeveloperGroupUserPermissions',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='developercontenttype',
            options={'verbose_name': 'developer content type', 'verbose_name_plural': 'developer content types'},
        ),
        migrations.AlterModelOptions(
            name='developergroup',
            options={'verbose_name': 'developer group', 'verbose_name_plural': 'developer groups'},
        ),
        migrations.AlterModelOptions(
            name='developergroupuserpermissions',
            options={'verbose_name': 'developer group user permission', 'verbose_name_plural': 'developer group user permissions'},
        ),
        migrations.AlterModelManagers(
            name='companyuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='developercontenttype',
            table='developer_content_type',
        ),
        migrations.AlterModelTable(
            name='developergroup',
            table='developer_group',
        ),
        migrations.AlterModelTable(
            name='developergroupuserpermissions',
            table='developer_group_user_permission',
        ),
        migrations.RenameModel(
            old_name='ContentType',
            new_name='DeveloperContentType',
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='DeveloperGroup',
        ),
        migrations.RenameModel(
            old_name='UserPermissions',
            new_name='DeveloperUserPermissions',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='developerpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developercontenttype'),
        ),
        migrations.AddField(
            model_name='developergrouppermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.developergroup'),
        ),
        migrations.AddField(
            model_name='developergrouppermission',
            name='permission',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='developers.developerpermission'),
        ),
        migrations.AlterField(
            model_name='developeruserpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='developers.developerpermission'),
        ),
    ]
